### ISSUE TITLE
Can't find the respective color group for the line numbers themselves

### ISSUE THREAD

**Issue by z0xyz** [ful1e5/onedark.nvim#102]
I've tried to find a way to change the colors of line numbers (not the vertical line number as a whole), but found none . The docs does mention that it can be addressed with their `color group` but there isn't any listing of any !
If there is a direct method to alter this very component, then that would do that job. However if there's a more encompassing thorough list of all the alterable colors groups / components then that would be much more convenient, for further customization .

**Comment by ful1e5** [comment]
You can override the `LineNr` and `CursorLineNr` highlight using the `overrides` property.

```lua
require('onedark').setup({
  overrides = function(c)
    return {
      LineNr = { bg = '#000000', fg = '#ffffff' }, -- Line number for ":number" and ":#" commands, and when 'number' or 'relativenumber' option is set.
      CursorLineNr = { bg = '#000000', fg = '#ffffff' }, -- Like LineNr when 'cursorline' or 'relativenumber' is set for the cursor line.
    }
  end,
})
```

**Comment by ful1e5** [comment]
By overriding `pythonTSVariable` variable.

You can override the `LineNr` and `CursorLineNr` highlight using the `overrides` property.

```lua
require('onedark').setup({
  dev = true,
  overrides = function()
    return {
      pythonTSVariable = { bg = '#000000', fg = '#ffffff' },
    }
  end,
})
```
