### ISSUE TITLE
Minimal Status Line Bug

### ISSUE THREAD

**Issue by monsonjeremy** [ful1e5/onedark.nvim#2]
Here's what I found in my repo helped fix the issue for me. 

In my `packer` config I did the following

```lua
  use {
    'monsonjeremy/onedark.nvim',
    config = function()
      local utils = require('utils')
      require('plugins.onedark').setupOneDark()
      utils.apply_colorscheme("onedark", "dark")
    end
  }
```

and then inside of `plugins.onedark` I have
```lua
local M = {}

function M.setupOneDark()
  local utils = require('utils')

  utils.apply_globals({
    onedark_hide_inactive_statusline = true,
  })
end

return M
```

and utils:
```lua
local M = {}

function M.apply_globals(globals)
  for k, v in pairs(globals) do vim.g[k] = v end
end

function M.apply_colorscheme(name, mode)
  M.apply_options({
    termguicolors = true,
    background = mode
  })

  M.apply_globals({
    colors_name = name
  })

  vim.api.nvim_command('colorscheme ' .. name)
end

return M
```

Basically what I believe to be the issue is that the `onedark_hide_inactive_statusline` was not being set in time which was causing the highlights to be applied improperly. In order to fix that I tried to make sure that the value was set before the `colorscheme` was set.

Example:
<img width="1680" alt="Screen Shot 2021-06-14 at 6 22 50 PM" src="https://user-images.githubusercontent.com/8846086/121978660-88fe5300-cd3d-11eb-816d-219f436d7d8d.png">

**Comment by ful1e5** [comment]
try to set `onedark_hide_inactive_statusline` option individually  to **vim.g**.  This works for me (**video attached**).

https://user-images.githubusercontent.com/24286590/122028721-ebad2880-cde9-11eb-98c1-4dd93384dffd.mp4

Here is how I did in my `.vimrc`

```lua
vim.g.onedark_hide_inactive_statusline = true
-- Load the colorscheme
vim.cmd [[colorscheme onedark]]

```
##### Inside `packer`

```lua
use {
  "ful1e5/onedark.nvim",
  config = function()
    vim.g.onedark_hide_inactive_statusline = true

    -- Load the colorscheme
    vim.cmd [[colorscheme onedark]]
  end
}
```

**Comment by ful1e5** [comment]
@monsonjeremy Try to set the lualine config before onedark config. This works for me.

**Comment by monsonjeremy** [comment]
Hmm I can give that a try. It seems to me ultimately that using `packer.nvim` is part of the problem since it lazy-loads configuration/plugins. Is that incorrect?

**Comment by ful1e5** [comment]
`packer.nvim` lazy load works fine for me. As I said, This bug can be reproduced by changing the lualine and onedark '_config order_'.

https://user-images.githubusercontent.com/24286590/123260320-0fbbe880-d513-11eb-837b-ab60cd5aa9ae.mp4

**Comment by monsonjeremy** [comment]
Hmm I see what you mean, that makes sense. Is there any way to manage the execution order of these configs if they are in two different files using `packer.nvim`? If not I assume you're kind of required to have it in the same file.

Here's my config:
```lua
  use {
    'hoob3rt/lualine.nvim',
    config = function()
      print('lualine')
      require 'plugins.lualine'
    end
  }

  use {
    'monsonjeremy/onedark.nvim',
    config = function()
      local utils = require('utils')
      print('onedark')
      require('plugins.onedark').setupOneDark()
      utils.apply_colorscheme("onedark", "dark")
    end
  }
```

I tried to split each plugins config into it's own file, but with the print statements I see that `onedark` prints first, which is why I have the issue.

**Comment by monsonjeremy** [comment]
It works with your fork of my package, but not with mine 🤔 

Do you know if you changed anything that might have had an effect on that?
