### ISSUE TITLE
Does not do proper highlighting in typescript.

### ISSUE THREAD

**Issue by zarghamkhandev** [ful1e5/onedark.nvim#36]
![image](https://user-images.githubusercontent.com/61333365/132987623-b371c8b4-35c5-4c22-89b0-dab37bbda134.png)

Its not showing proper syntax highlighting for my typescript files.

**Comment by ful1e5** [comment]
Share you config

**Comment by zarghamkhandev** [comment]
![image](https://user-images.githubusercontent.com/61333365/132989188-f7766213-cb60-43ef-91f5-755cc7dd219b.png)

**Comment by ful1e5** [comment]
This is colorscheme is written lua.  So, You have to call `setup` function.
```vim
if(has(termguicolors))
  set termguicolors
endif
" Onedark Theme
syntax enable
lua require("onedark").setup()
```
Check [README#Configuration](https://github.com/ful1e5/onedark.nvim#%EF%B8%8F-configuration) for option.
