### ISSUE TITLE
Highlighting cannot be overwritten

### ISSUE THREAD

**Issue by edwarmv** [ful1e5/onedark.nvim#70]
Hi, I am not able to overwrite the vim-illuminate highlights with the following configuration

```
require("onedark").setup()
vim.cmd([[hi illuminatedCurWord ctermbg=242 guibg=#393f4a]])
vim.cmd([[hi illuminatedWord ctermbg=242 guibg=#393f4a]])
```

Thanks for the colorscheme

**Comment by Nauticus** [comment]
Hi, I've faced the same issue and after spending some time digging around the code I found the culprit. Looks like there is vim.defer_fn call after base theme is loaded. My solution is to defer my overrides after 101 ms which would supersede the defaults:
`
            require("onedark").setup()

            local utils = require("onedark.util")

            vim.defer_fn(function()
                utils.syntax({ NvimTreeFolderName = { fg = colors.blue, bg = colors.red } })
            end, 101) -- 101 is the important part here
`

Cheers!
