### ISSUE TITLE
Toggleterm colors don't match terminal theme

### ISSUE THREAD

**Issue by ByteDrummer** [ful1e5/onedark.nvim#95]
First of all, thanks for this plugin. I'm having an issue where the wrong colors are applied to text in the toggleterm buffer. The text autocompletion in the pictures below looks too dark, and so does the gray part of the prompt. Is there an option that lets me correct this?

Terminal in nvim:
![Screenshot from 2022-01-15 18-17-38](https://user-images.githubusercontent.com/14875006/149644795-7ab7de1e-4010-4541-93e7-9909aefca59e.png)

Terminal outside nvim:
![Screenshot from 2022-01-15 18-18-21](https://user-images.githubusercontent.com/14875006/149644802-2d1a912a-4e9b-4424-9dd1-0f222af7c506.png)

**Comment by ful1e5** [comment]
Fixed in 8ca0d4c07760d107ab19d675f95bb84a884e3cf2 .
