### ISSUE TITLE
Tmux support

### ISSUE THREAD

**Issue by melkster** [ful1e5/onedark.nvim#96]
Is this colorscheme supposed to look the same in tmux? To me the colors look odd in tmux. I've read online that the following should make colorschemes look the same in tmux, but it doesn't seem to work. Is it became this colorscheme doesn't support 24-bit RGB colors?

```vim
if exists('$TMUX')
  set notermguicolors
endif
```

To the left in the screenshot below is what the colorscheme looks when not using tmux, and to the right is how it looks when Neovim is running inside of tmux:

![neovim in tmux](https://user-images.githubusercontent.com/15816726/149953593-a93fb654-9c16-4639-bde1-e6a02894ea69.png)

**Comment by ful1e5** [comment]
This theme is working fine to me though. I ran it with tmux and without but can't find any color difference.
![image](https://user-images.githubusercontent.com/24286590/150673623-dce0f622-7e19-4eca-aa0b-4e8797f8167b.png)

I also did quick google about your issue and found some StackOverflow regarding this issue. I hope this helps you :crossed_fingers:
https://stackoverflow.com/questions/10158508/lose-vim-colorscheme-in-tmux-mode/41626377
https://stackoverflow.com/questions/66757229/vim-not-using-proper-colorscheme-in-tmux

**Comment by melkster** [comment]
I had already tried everything in the first link without success before posting here, but after trying the solution in your second link I got it working by adding this to my `~/.tmux.conf`:

```tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
```

Thank you :)
